import { AlertTriangle, ArrowRightLeft, BadgeCheck, Boxes, Clock3, ShieldAlert, Wrench } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { formatDateTime } from "../lib/formatters";
import { SectionHeader } from "../components/SectionHeader";
import { StatCard } from "../components/StatCard";
import { StatusBadge } from "../components/StatusBadge";

const pieColors = ["#0c6fa8", "#45a1ff", "#f0b63a", "#e26363", "#94a3b8"];

export function DashboardPage({
  assets,
  departments,
  activities,
  checkoutLogs,
  maintenanceSchedules,
  securityLogs,
  utilizationTrend,
}) {
  const departmentDistribution = departments.map((department) => ({
    name: department.name,
    total: assets.filter((asset) => asset.department === department.name).length,
  }));

  const statusDistribution = [
    { name: "Active", value: assets.filter((asset) => asset.status === "Active").length },
    { name: "Checked Out", value: assets.filter((asset) => asset.status === "Checked Out").length },
    { name: "Maintenance", value: assets.filter((asset) => asset.status === "Maintenance Due").length },
    { name: "Repair", value: assets.filter((asset) => asset.status === "Under Repair").length },
    { name: "Aging", value: assets.filter((asset) => asset.status === "Aging").length },
  ];

  const alerts = [
    ...maintenanceSchedules.filter((entry) => entry.status === "Overdue").map((entry) => ({
      id: entry.id,
      title: `${entry.assetName} missed maintenance`,
      detail: `${entry.department} ${entry.cadence.toLowerCase()} service is overdue.`,
      status: "Alert",
    })),
    ...checkoutLogs.filter((entry) => entry.status === "Overdue").map((entry) => ({
      id: entry.id,
      title: `${entry.assetName} is overdue`,
      detail: `${entry.person} has not returned the checked-out asset.`,
      status: "Alert",
    })),
    ...securityLogs.filter((entry) => entry.status === "Flagged" || entry.status === "Unverified").map((entry) => ({
      id: entry.id,
      title: `${entry.assetName} needs verification`,
      detail: `${entry.method} at ${entry.location} produced ${entry.status.toLowerCase()} status.`,
      status: entry.status,
    })),
  ];

  return (
    <div className="space-y-8 page-enter">
      <SectionHeader
        eyebrow="Dashboard"
        title="Asset command center"
        description="A premium operational overview spanning asset health, department distribution, and live verification exposure."
      />

      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
        <StatCard
          icon={Boxes}
          label="Total Assets"
          value={assets.length}
          detail="Tracked asset lines across every department."
          trend="+8% QoQ"
        />
        <StatCard
          icon={BadgeCheck}
          label="Active Pool"
          value={assets.filter((asset) => asset.status === "Active").length}
          detail="Assets currently in standard operational circulation."
          tone="green"
        />
        <StatCard
          icon={Wrench}
          label="Repair & Service"
          value={assets.filter((asset) => asset.status === "Under Repair" || asset.status === "Maintenance Due").length}
          detail="Assets demanding service attention or vendor action."
          tone="amber"
        />
        <StatCard
          icon={ShieldAlert}
          label="Flagged Risk"
          value={alerts.length}
          detail="Exceptions generated by overdue, unverified, or aging assets."
          tone="red"
        />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.35fr_0.95fr]">
        <div className="panel">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[var(--color-brand-600)]">Utilization Trend</p>
              <h2 className="mt-2 font-display text-2xl text-[var(--color-ink-950)]">Operational stability across the last 6 months</h2>
            </div>
            <div className="rounded-full bg-[var(--color-brand-50)] px-4 py-2 text-xs font-semibold uppercase tracking-[0.22em] text-[var(--color-brand-700)]">
              Readiness improving
            </div>
          </div>
          <div className="mt-8 h-[320px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={utilizationTrend}>
                <defs>
                  <linearGradient id="activeFill" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#0c6fa8" stopOpacity={0.35} />
                    <stop offset="100%" stopColor="#0c6fa8" stopOpacity={0.02} />
                  </linearGradient>
                </defs>
                <XAxis dataKey="month" stroke="#7185a3" axisLine={false} tickLine={false} />
                <YAxis stroke="#7185a3" axisLine={false} tickLine={false} />
                <Tooltip />
                <Area type="monotone" dataKey="active" stroke="#0c6fa8" strokeWidth={3} fill="url(#activeFill)" />
                <Area type="monotone" dataKey="maintenance" stroke="#f0b63a" strokeWidth={2} fill="transparent" />
                <Area type="monotone" dataKey="alerts" stroke="#d95757" strokeWidth={2} fill="transparent" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="panel">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[var(--color-brand-600)]">Risk Queue</p>
          <div className="mt-3 flex items-center justify-between">
            <h2 className="font-display text-2xl text-[var(--color-ink-950)]">Priority alerts</h2>
            <span className="rounded-full border border-rose-200 bg-rose-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-rose-700">
              {alerts.length} open
            </span>
          </div>
          <div className="mt-6 space-y-4">
            {alerts.map((alert) => (
              <div key={alert.id} className="rounded-[1.5rem] border border-[var(--color-line)] bg-[var(--color-shell-50)]/65 p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold text-[var(--color-ink-950)]">{alert.title}</p>
                    <p className="mt-1 text-sm leading-6 text-[var(--color-ink-500)]">{alert.detail}</p>
                  </div>
                  <StatusBadge value={alert.status} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr_0.9fr]">
        <div className="panel">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[var(--color-brand-600)]">Department Spread</p>
          <h2 className="mt-2 font-display text-2xl text-[var(--color-ink-950)]">Asset distribution by department</h2>
          <div className="mt-8 h-[280px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={departmentDistribution}>
                <XAxis dataKey="name" stroke="#7185a3" axisLine={false} tickLine={false} />
                <YAxis stroke="#7185a3" axisLine={false} tickLine={false} />
                <Tooltip />
                <Bar dataKey="total" fill="#0c6fa8" radius={[14, 14, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="panel">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[var(--color-brand-600)]">Status Mix</p>
          <h2 className="mt-2 font-display text-2xl text-[var(--color-ink-950)]">Current asset posture</h2>
          <div className="mt-4 h-[280px]">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={statusDistribution} dataKey="value" nameKey="name" innerRadius={68} outerRadius={104} paddingAngle={5}>
                  {statusDistribution.map((entry, index) => (
                    <Cell key={entry.name} fill={pieColors[index % pieColors.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="grid gap-3 sm:grid-cols-2">
            {statusDistribution.map((entry, index) => (
              <div key={entry.name} className="rounded-[1.25rem] border border-[var(--color-line)] bg-white px-4 py-3">
                <div className="flex items-center gap-3">
                  <span className="size-3 rounded-full" style={{ backgroundColor: pieColors[index % pieColors.length] }} />
                  <p className="text-sm font-medium text-[var(--color-ink-500)]">{entry.name}</p>
                </div>
                <p className="mt-2 font-display text-2xl text-[var(--color-ink-950)]">{entry.value}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="panel">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[var(--color-brand-600)]">Recent Activity</p>
          <h2 className="mt-2 font-display text-2xl text-[var(--color-ink-950)]">Live operations feed</h2>
          <div className="mt-6 space-y-4">
            {activities.map((activity) => (
              <div key={activity.id} className="rounded-[1.5rem] border border-[var(--color-line)] bg-[var(--color-shell-50)]/70 p-4">
                <div className="flex gap-3">
                  <div className="mt-1 inline-flex size-9 shrink-0 items-center justify-center rounded-2xl bg-[var(--color-brand-100)] text-[var(--color-brand-700)]">
                    <ArrowRightLeft className="size-4" />
                  </div>
                  <div>
                    <p className="font-semibold text-[var(--color-ink-950)]">{activity.title}</p>
                    <p className="mt-1 text-sm leading-6 text-[var(--color-ink-500)]">{activity.detail}</p>
                    <div className="mt-3 inline-flex items-center gap-2 text-xs uppercase tracking-[0.22em] text-[var(--color-ink-400)]">
                      <Clock3 className="size-3.5" />
                      {formatDateTime(activity.timestamp)}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="panel-alt">
          <div className="flex items-start gap-3">
            <AlertTriangle className="mt-1 size-5 text-rose-600" />
            <div>
              <p className="font-semibold text-[var(--color-ink-950)]">Overdue maintenance</p>
              <p className="mt-1 text-sm leading-6 text-[var(--color-ink-500)]">AC Unit Daikin and Generator 10KVA already crossed their service due dates.</p>
            </div>
          </div>
        </div>
        <div className="panel-alt">
          <div className="flex items-start gap-3">
            <ShieldAlert className="mt-1 size-5 text-amber-600" />
            <div>
              <p className="font-semibold text-[var(--color-ink-950)]">Unauthorized movement watch</p>
              <p className="mt-1 text-sm leading-6 text-[var(--color-ink-500)]">Generator transfer is pending approval and still outside the approved yard state.</p>
            </div>
          </div>
        </div>
        <div className="panel-alt">
          <div className="flex items-start gap-3">
            <Boxes className="mt-1 size-5 text-[var(--color-brand-700)]" />
            <div>
              <p className="font-semibold text-[var(--color-ink-950)]">Aging portfolio</p>
              <p className="mt-1 text-sm leading-6 text-[var(--color-ink-500)]">One end-of-life generator and one poor-condition HVAC unit should enter replacement planning.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
